_target_: navsim.agents.diffusiondrive.transfuser_agent.TransfuserAgent
_convert_: 'all'

config:
  _target_: navsim.agents.diffusiondrive.transfuser_config.TransfuserConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False
  use_risk_gate: False
  use_historical_risk_attention: True
  use_temporal_risk_cross_attention: False
  use_memory_aux_loss: True
  use_risk_aware_cls: True
  use_step_brake_timing_loss: False
  use_risk_shadow_evaluator: True
  use_soft_risk_rescore: False

checkpoint_path: null
lr: 6e-4
